mod 'puppet-nginx', '1.1.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/stdlib'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs/docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/pwshlib'
mod 'puppetlabs/reboot'
